### ISSUE TITLE
Issue in the F file

### ISSUE THREAD

**Issue by MarioDipoppa** [cortex-lab/Suite2P#12]
In an F file generated by suite2P, for one cell number #icell
stat(#icell).ipix
is an empty array. Is this normal?

This create a bug later in createNeuropilMask when it is trying to compute the centroid

**Comment by marius10p** [comment]
I think it's possible that a parent ROI has been completed converted into a child and there are no leftover pixels. So that ROI will never be chosen in the GUI or anywhere, it's just not relevant. 

However, I know you only compute the neuropil masks for children ROIs, right? Those always have to be at least Nmin pixels, something like 30 or so. Anyway, if a ROI is empty, you don't need to compute neuropil masks: it will never be used.

**Comment by xigumalu** [comment]
Hi Marius,

you're right. Mario was only calculating neuropil for children ROI. I 
just changed the code so that all ROIs are considered (as it happened 
that I also picked parent ROIs as good ROIs). Will add a check for empty 
pixel arrays.
