### ISSUE TITLE
Saving error in the main GUI

### ISSUE THREAD

**Issue by geffenlab** [cortex-lab/Suite2P#41]
Hi
I am getting a save error after I have processed in the main GUI, this message appears when I press the 'save proc file' button:

"Reference to non-existent field 'statLabels'.

Error in new_main>pushbutton84_Callback (line 222)
statLabels  = h.statLabels;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in new_main (line 17)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)new_main('pushbutton84_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback"

Any idea why this might be happening?

Thanks,
Kath

**Comment by marius10p** [comment]
Hi Kath,

We had a complete pipeline overhaul recently, with several improvements across all processing stages including the GUI. Unfortunately, data processed with older versions is probably no longer compatible with the new version, which might be what your error was. Otherwise, it might be a new bug that this new version introduced, just let me know.

**Comment by woodkath** [comment]
​Hi Marius

You were right, I thought I had the most recent version but I must not have
- all is good now. Sorry for the bother!

All the best,
Kath​




On 20 Jan 2017, at 11:09, Marius Pachitariu <notifications@github.com>
wrote:

Hi Kath,

We had a complete pipeline overhaul recently, with several improvements
across all processing stages including the GUI. Unfortunately, data
processed with older versions is probably no longer compatible with the new
version, which might be what your error was. Otherwise, it might be a new
bug that this new version introduced, just let me know.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cortex-lab/Suite2P/issues/41#issuecomment-274110362>,
or mute the thread

**Comment by woodkath** [comment]
Marius, this may seem a stupid question but the traces you get out
(i.e. dat.Fcell) do they already have neuropil subtracted or not?

Kath

**Comment by marius10p** [comment]
They do not have neuropil subtracted. Sorry, one of these days, I will write a comprehensive User's Guide. 

There is another set of traces dat.FcellNeu, which are neuropil for each cell.  Choosing the correct neuropil subtraction coefficient should be done carefully. In some papers it is just set to 0.7. In others it is based on maximizing the skewness of the corrected trace, which is what we do. You can find this number in stat(icell).neuropilCoefficient. 

But I always advise caution with respect to neuropil subtraction: if it seems like it might influence your result, try seeing if you still get the result with different values of neuropil subtraction coefficients.

**Comment by woodkath** [comment]
OK - great, thanks for the advice,

Thanks!
Kath

**Comment by woodkath** [comment]
Actually, I don't see the stat.neuropilCoefficient in my output though...?
I just have these fields in the stat structure - (sorry!):
mrs
    mrs0
    cmpct
    ipix
    xpix
    ypix
    lam
    lambda
    npix
    med
    footprint
    mimgProj
    mimgProjAbs
    dFstat
    skew
    std
    maxMinusMed
    top5pcMinusMed
    blockstarts
    iplane
    iscell
    cellProb
    redcell
    redprob

**Comment by kauttoj** [comment]
Error with the "h.statLabels" seems a bug. When saving F*_proc.mat files, "statLabels" field is not saved. However, if one opens some F_*.mat file before any F*_proc.mat files, no error occurs since 'h.statLabels' is constructed.
To fix, one can add "dat.statLabels = h.statLabels;" into "pushbutton84_Callback" function and "h.statLabels = h.dat.statLabels;" when F*_proc.mat file is loaded.

**Comment by marius10p** [comment]
Sorry, missed your previous message. The answer was that the neuropilCoefficient field is only added if you run the spike deconvolution; it's part of the post-processing. 

Thanks for point out the bug with statLabels. I guess we didn't catch that because we don't usually open the proc files back again....

**Comment by marius10p** [comment]
Loading back the proc file should work now.
