### ISSUE TITLE
Slow drifts in the data (should I worry?)

### ISSUE THREAD

**Issue by kauttoj** [cortex-lab/Suite2P#43]
Hi

This is not really an issue/defect on Suite2P, but a more general question about Suite2P capabilities.

In our data there is occasionally noticeable slow mean intensity drifting, which leads to large discontinuities when multiple files are joined together. I the example dataset shown here, I have joined together 26 recording sessions with total length of 86min. Mean signal intensity decreases slowly for all ROIs, until baseline is recovered at mid experiment (more water was added over the window).

Can Suite2P process this type of data reliably? 
What kind of effect such large drifts/discontinuities have on ROI clustering, neuropil estimation and deconvolution?

I could try to remove these drifts after alignment is finished (that huge .bin file). Some high-pass filtering/regression should do the trick.

![water_loss_example_2068_2r_170124](https://cloud.githubusercontent.com/assets/17804946/22440857/0ed71b22-e703-11e6-887c-0ddeadc03d08.png)

**Comment by marius10p** [comment]
Hi,

The drift and discontinuity will not matter for the purpose of finding the ROIs, but you have to be careful interpreting the fluorescence traces. 

If the baseline drift was just an additive drift, it would be the same in the neuropil and cell, and thus the neuropil subtraction would take care of it. But it's more likely to be a multiplicative drift, meaning the transients will get smaller when the baseline is lower. To deal with that correctly, you would need to add back the mean to each trace (Fcell and FcellNeu), then estimate the drift as a baseline, and compute the dF/F from that, for both the cell signal and neuropil. 

I will keep this issue open, to remind myself to do this at some point, but I won't have time for the next few weeks.

**Comment by kauttoj** [comment]
Thanks for the reply. 
I did some testing for this data and yes, it is indeed multiplicative drift that affects both baseline and variance. Fixing only the baseline is not too useful. I run this dataset three times
(1) standard Suite2P (no modifications)
(2) intensity normalization, where each data-part is multiplied by a factor x/y, where x=weighted mean intensity over all parts and y=mean of each part
(3) intensity normalization followed by independent detrending for each part

Results are shown below.  I have chosen the same segment (neuron) for each case. As you said, there is no notable effect on ROI detection. There are some differences on segment classification, which is expected since stats for segments are different.

![fig1_standard_no_corrections](https://cloud.githubusercontent.com/assets/17804946/22696458/0e8426b4-ed1c-11e6-8f74-efc249e1863c.png)
![fig2_intensity_correction](https://cloud.githubusercontent.com/assets/17804946/22696464/11144f3a-ed1c-11e6-8ad6-95f5a2e39c27.png)
![fig3_intensity_fix_and_detrending](https://cloud.githubusercontent.com/assets/17804946/22696467/130bbb16-ed1c-11e6-9cb5-773206be3293.png)

**Comment by kauttoj** [comment]
Can you clarify how I can add baseline back? Is all necessary information available in F_*.mat file or do I need to make some tweaks? There is no longer baseline variable 'dat.cl.dcell{i}.B(2)' as mentioned in readme.

Related question: How can I convert final Fcell traces into standard dF/F0 units, i.e., percentage change from the baseline?

**Comment by marius10p** [comment]
Sorry for taking so long to fix this, and thanks for providing all the information, it was helpful. 

Your code was fairly close, but I had to add a few things. The new version adds back the means of both the neuropil and the cell activity. I have verified in one recording that this makes everything positive, except for very rare, very slightly negative samples. I think this a consequence of shot noise. The neuropil is estimated smoothly from a large part of the field of view, but the estimated cell activity is local cellular + local neuropil - long range neuropil estimate. So the cell activity can be inferred to be negative, but that should only happen on single frames, not consistently  across frames. 

Let me know if there are still issue. Following extraction, you can estimate a running baseline for the neuropil corrected traces, and normalize by that. Up to you, I'd rather not include any post-processing directly into the pipeline, so that users  can choose their own post-processing.
