### ISSUE TITLE
Not having an Nvidia GPU

### ISSUE THREAD

**Issue by imorozovuottawa** [cortex-lab/Suite2P#72]
Hello,

 I've just started using your software and not able to make recordings, because my machine does not have an Nvidia GPU (my machine has an AMD RADEON(TM) R5 340X graphic card).
Would be it possible to use other graphics cards with Suite2P to make recordings?
If not, what Nvidia  graphics card would you recommend to use with Suite2P to make recordings.

Thanks,

Irina

**Comment by marius10p** [comment]
Hi Irina. To run Suite2p you do not necessarily need a GPU. Just make sure you set the ops.useGPU = 0 in the master_file. It is not currently possible to use AMD GPUs, because Matlab does not support them. An entry-level GTX GPU like GTX 1060 would work well with Suite2p and give you a 2-4x speedup depending on the configuration (the speedup is just for registration). Cheers, -Marius
