### ISSUE TITLE
Error when writing tiffs to file

### ISSUE THREAD

**Issue by ehennestad** [cortex-lab/Suite2P#92]
Any idea why this might happen?
```
running rigid registration
bi-directional scanning offset = 0 pixels
Set 1, tiff 1 done in time 120.58 
Set 2, tiff 1 done in time 243.63 
Set 3, tiff 1 done in time 366.55 
Index exceeds matrix dimensions.

Error in TiffWriter (line 20)
t.write(image(:,:,1));

Error in write_reg_to_tiff (line 42)
        TiffWriter(int16(data),fname,bitspersamp);

Error in reg2P (line 290)
        ops1{i} = write_reg_to_tiff(fid{i}, ops1{i}, i);

Error in run_pipeline (line 57)
        ops1 = reg2P(ops);  % do registration

Error in s2p_master_file_eivind (line 89)
    run_pipeline(db, ops0);
```

**Comment by ehennestad** [comment]
Might have happened because my files are tifffiles are 8bit

**Comment by marius10p** [comment]
It's probably because of that, sorry. It looks like you are trying to write the registered movie to tiffs (this is only for ease of visual inspection, as the registered movies get automatically written to a binary file). Can you please tell me if the pipeline runs through fine without writing the registered tiffs? In that case, I will know the problem is confined to the TiffWriter segment.

**Comment by ehennestad** [comment]
Yes, exactly - I need to check the results of the registered images. I changed the relevant parts of the code to save the registered tiffs as uint8 and then it worked well, also for the rest of the pipeline.

**Comment by carsen-stringer** [comment]
I've added a function to check from the binary files in the main directory (view_registered_binaries.m). This will be a faster solution to looking at the tiffs themselves if you want to try it out.
